port: 2000
socks-port: 2345
allow-lan: true
mixed-port: 2020
mode: rule
ipv6: true
log-level: info
bind-address: '*'
external-controller: :9090
interface-name: en0
hosts:
  'mtalk.google.com': 108.177.125.188

profile:
  store-selected: false

dns:
  enable: false
  #listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - 119.29.29.29
    - 223.6.6.6
    - https://223.6.6.6/dns-query

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - router.asus.com
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - '+.msftconnecttest.com'
tun:
  enable: false
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.8.8

proxy-providers:
  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹:
    type: http
    path: ./Proxy/HK.yaml
    url: https://api.io/getprofile?name=Clash/HK.ini&token=XX
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹:
    type: http
    path: ./Proxy/KR.yaml
    url: https://api.io/getprofile?name=Clash/KR.ini&token=XX
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹:
    type: http
    path: ./Proxy/SG.yaml
    url: https://api.io/getprofile?name=Clash/SG.ini&token=XX
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹:
    type: http
    path: ./Proxy/US.yaml
    url: https://api.io/getprofile?name=Clash/US.ini&token=XX
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  ğŸ‡ºğŸ‡³ å…¶å®ƒèŠ‚ç‚¹:
    type: http
    path: ./Proxy/Others.yaml
    url: https://api.io/getprofile?name=Clash/Others.ini&token=XX
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  ğŸ“§ è§£é”èŠ‚ç‚¹:
    type: http
    path: ./Proxy/NE.yaml
    url: https://api.io/getprofile?name=Clash/NE.ini&token=XX
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  ğŸ‡¨ğŸ‡³ å¤§é™†èŠ‚ç‚¹:
    type: http
    path: ./Proxy/CN.yaml
    url: https://api.io/getprofile?name=Clash/CN.ini&token=XX
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: ğŸ’Œ å¸¸ç”¨æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ºğŸ‡³ å…¶å®ƒ
      - ğŸ‡¨ğŸ‡³ å¤§é™†
  - name: ğŸ–¥ æˆ‘çš„æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ºğŸ‡³ å…¶å®ƒ
      - ğŸ‡¨ğŸ‡³ å¤§é™†
  - name: ğŸ“§ ç½‘æ˜“äº‘æ‘
    type: select
    proxies:
      - DIRECT
      - ğŸ“§ è§£é”
  - name: ğŸ¬ å¥ˆéå½±è§†
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ºğŸ‡³ å…¶å®ƒ
  - name: ğŸ‘’ ä¸­å°åª’ä½“
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ºğŸ‡³ å…¶å®ƒ
      - ğŸ‡¨ğŸ‡³ å¤§é™†
  - name: ğŸ“¸ å¢ƒå¤–åª’ä½“
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ºğŸ‡³ å…¶å®ƒ
      - ğŸ‡¨ğŸ‡³ å¤§é™†
  - name: ğŸ›« å¢ƒå¤–æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ºğŸ‡³ å…¶å®ƒ
      - ğŸ‡¨ğŸ‡³ å¤§é™†
  - name: ğŸ” å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸ”˜ é»‘ç™½åå•
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡ºğŸ‡³ å…¶å®ƒ
      - ğŸ‡¨ğŸ‡³ å¤§é™†
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯
    type: select
    proxies:
    use:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  - name: ğŸ‡°ğŸ‡· éŸ©å›½
    type: select
    proxies:
    use:
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
    type: select
    proxies:
    use:
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½
    type: select
    proxies:
    use:
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
  - name: ğŸ‡ºğŸ‡³ å…¶å®ƒ
    type: select
    proxies:
    use:
      - ğŸ‡ºğŸ‡³ å…¶å®ƒèŠ‚ç‚¹
  - name: ğŸ“§ è§£é”
    type: select
    proxies:
    use:
      - ğŸ“§ è§£é”èŠ‚ç‚¹
  - name: ğŸ‡¨ğŸ‡³ å¤§é™†
    type: select
    proxies:
    use:
      - ğŸ‡¨ğŸ‡³ å¤§é™†èŠ‚ç‚¹  

rule-providers:
  Direct:
    type: http
    behavior: classical
    path: ./RuleSet/Direct.yaml
    url: https://hub.qste.com/Clash/Ruleset/Direct.yml
    interval: 86400
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://hub.qste.com/Clash/Ruleset/Unbreak.yml
    interval: 86400
  AdWhiteList:
    type: http
    behavior: classical
    path: ./RuleSet/AdWhiteList.yaml
    url: https://hub.qste.com/Clash/Ruleset/AdWhiteList.yml
    interval: 86400
  Advertising:
    type: http
    behavior: classical
    path: ./RuleSet/Advertising.yaml
    url: https://hub.qste.com/Clash/Ruleset/Advertising.yml
    interval: 86400
  Hijacking:
    type: http
    behavior: classical
    path: ./RuleSet/Hijacking.yaml
    url: https://hub.qste.com/Clash/Ruleset/Hijacking.yml
    interval: 86400
  Privacy:
    type: http
    behavior: classical
    path: ./RuleSet/Privacy.yaml
    url: https://hub.qste.com/Clash/Ruleset/Privacy.yml
    interval: 86400
  Custom:
    type: http
    behavior: classical
    path: ./RuleSet/Custom.yaml
    url: https://hub.qste.com/Clash/Ruleset/Custom.yml
    interval: 86400
  MySite:
    type: http
    behavior: classical
    path: ./RuleSet/MySite.yaml
    url: https://hub.qste.com/Clash/Ruleset/MySite.yml
    interval: 86400
  SpeedTest:
    type: http
    behavior: classical
    path: ./RuleSet/SpeedTest.yaml
    url: https://hub.qste.com/Clash/Ruleset/SpeedTest.yml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    path: ./RuleSet/Netflix.yaml
    url: https://hub.qste.com/Clash/Ruleset/Netflix.yml
    interval: 86400
  HKMTMedia:
    type: http
    behavior: classical
    path: ./RuleSet/HKMTMedia.yaml
    url: https://hub.qste.com/Clash/Ruleset/HKMTMedia.yml
    interval: 86400
  AppleSpecial:
    type: http
    behavior: classical
    path: ./RuleSet/AppleSpecial.yaml
    url: https://hub.qste.com/Clash/Ruleset/AppleSpecial.yml
    interval: 86400
  iCloud:
    type: http
    behavior: classical
    path: ./RuleSet/iCloud.yaml
    url: https://hub.qste.com/Clash/Ruleset/iCloud.yml
    interval: 86400
  Apple:
    type: http
    behavior: classical
    path: ./RuleSet/Apple.yaml
    url: https://hub.qste.com/Clash/Ruleset/Apple.yml
    interval: 86400
  NeteaseMusic:
    type: http
    behavior: classical
    path: ./RuleSet/NeteaseMusic.yaml
    url: https://hub.qste.com/Clash/Ruleset/NeteaseMusic.yml
    interval: 86400
  DomesticMedia:
    type: http
    behavior: classical
    path: ./RuleSet/DomesticMedia.yaml
    url: https://hub.qste.com/Clash/Ruleset/DomesticMedia.yml
    interval: 86400
  Akamai:
    type: http
    behavior: classical
    path: ./RuleSet/Akamai.yaml
    url: https://hub.qste.com/Clash/Ruleset/Akamai.yml
    interval: 86400
  Dropbox:
    type: http
    behavior: classical
    path: ./RuleSet/Dropbox.yaml
    url: https://hub.qste.com/Clash/Ruleset/Dropbox.yml
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    path: ./RuleSet/OneDrive.yaml
    url: https://hub.qste.com/Clash/Ruleset/OneDrive.yml
    interval: 86400
  Oracle:
    type: http
    behavior: classical
    path: ./RuleSet/Oracle.yaml
    url: https://hub.qste.com/Clash/Ruleset/Oracle.yml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: ./RuleSet/Microsoft.yaml
    url: https://hub.qste.com/Clash/Ruleset/Microsoft.yml
    interval: 86400
  TikTok:
    type: http
    behavior: classical
    path: ./RuleSet/TikTok.yaml
    url: https://hub.qste.com/Clash/Ruleset/TikTok.yml
    interval: 86400
  Twitter:
    type: http
    behavior: classical
    path: ./RuleSet/Twitter.yaml
    url: https://hub.qste.com/Clash/Ruleset/Twitter.yml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Telegram.yaml
    url: https://hub.qste.com/Clash/Ruleset/Telegram.yml
    interval: 86400
  Instagram:
    type: http
    behavior: classical
    path: ./RuleSet/Instagram.yaml
    url: https://hub.qste.com/Clash/Ruleset/Instagram.yml
    interval: 86400
  GoogleSearch:
    type: http
    behavior: classical
    path: ./RuleSet/GoogleSearch.yaml
    url: https://hub.qste.com/Clash/Ruleset/GoogleSearch.yml
    interval: 86400
  GooglePhotos:
    type: http
    behavior: classical
    path: ./RuleSet/GooglePhotos.yaml
    url: https://hub.qste.com/Clash/Ruleset/GooglePhotos.yml
    interval: 86400
  GoogleDrive:
    type: http
    behavior: classical
    path: ./RuleSet/GoogleDrive.yaml
    url: https://hub.qste.com/Clash/Ruleset/GoogleDrive.yml
    interval: 86400
  Google:
    type: http
    behavior: classical
    path: ./RuleSet/Google.yaml
    url: https://hub.qste.com/Clash/Ruleset/Google.yml
    interval: 86400
  PayPal:
    type: http
    behavior: classical
    path: ./RuleSet/PayPal.yaml
    url: https://hub.qste.com/Clash/Ruleset/PayPal.yml
    interval: 86400
  ForeignMedia:
    type: http
    behavior: classical
    path: ./RuleSet/ForeignMedia.yaml
    url: https://hub.qste.com/Clash/Ruleset/ForeignMedia.yml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://hub.qste.com/Clash/Ruleset/China.yml
    interval: 86400
  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://hub.qste.com/Clash/Ruleset/Global.yml
    interval: 86400
  Proxy:
    type: http
    behavior: classical
    path: ./RuleSet/Proxy.yaml
    url: https://hub.qste.com/Clash/Ruleset/Proxy.yml
    interval: 86400
  Block:
    type: http
    behavior: classical
    path: ./RuleSet/Block.yaml
    url: https://hub.qste.com/Clash/Ruleset/Block.yml
    interval: 86400
  LAN:
    type: http
    behavior: classical
    path: ./RuleSet/LAN.yaml
    url: https://hub.qste.com/Clash/Ruleset/LAN.yml
    interval: 86400

rules:
  - RULE-SET,Direct,DIRECT
  - RULE-SET,LAN,DIRECT
  - RULE-SET,Unbreak,ğŸ” å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,AdWhiteList,ğŸ” å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,Advertising,ğŸ” å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,Hijacking,ğŸ” å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,Privacy,ğŸ” å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,Custom,DIRECT
  - RULE-SET,MySite,ğŸ–¥ æˆ‘çš„æœåŠ¡
  - RULE-SET,SpeedTest,ğŸ¬ å¥ˆéå½±è§†
  - RULE-SET,Netflix,ğŸ¬ å¥ˆéå½±è§†
  - RULE-SET,HKMTMedia,ğŸ‘’ ä¸­å°åª’ä½“
  - RULE-SET,AppleSpecial,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,iCloud,DIRECT
  - RULE-SET,Apple,DIRECT
  - RULE-SET,NeteaseMusic,ğŸ“§ ç½‘æ˜“äº‘æ‘
  - RULE-SET,DomesticMedia,DIRECT
  - RULE-SET,Akamai,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,Dropbox,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,OneDrive,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,Oracle,DIRECT
  - RULE-SET,Microsoft,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,TikTok,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,Twitter,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,Telegram,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,Instagram,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,GoogleSearch,ğŸ›« å¢ƒå¤–æœåŠ¡
  - RULE-SET,GooglePhotos,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,GoogleDrive,ğŸ’Œ å¸¸ç”¨æœåŠ¡
  - RULE-SET,Google,ğŸ›« å¢ƒå¤–æœåŠ¡
  - RULE-SET,PayPal,ğŸ›« å¢ƒå¤–æœåŠ¡
  - RULE-SET,ForeignMedia,ğŸ“¸ å¢ƒå¤–åª’ä½“
  - RULE-SET,Global,ğŸ›« å¢ƒå¤–æœåŠ¡
  - RULE-SET,Proxy,ğŸ›« å¢ƒå¤–æœåŠ¡
  - RULE-SET,Block,ğŸ›« å¢ƒå¤–æœåŠ¡
  - RULE-SET,China,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸ”˜ é»‘ç™½åå•
