name: Update GeoIPs

on:
  workflow_dispatch:
#   push:
#     branches:
#       - "Her"
#     paths-ignore:
#       - "LICENSE"
#       - "*.md"
#       - "**/*.md"
#       - ".*"
#       - "node_modules"
  #schedule:
  #  - cron: 0 */24 * * *
jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get GeoIPs
      run: |
        cd $GITHUB_WORKSPACE
        cd GeoIP
        wget -N --no-check-certificate https://github.com/xOS/Country.mmdb/raw/release/Country.mmdb
        wget -NO Country-lite.mmdb --no-check-certificate https://github.com/xOS/Country.mmdb/raw/release/Country-lite.mmdb
        wget -N --no-check-certificate https://raw.githubusercontent.com/xOS/GeoIPs/release/Country-only-cn-private.mmdb
        wget -N --no-check-certificate https://raw.githubusercontent.com/xOS/GeoIPs/release/geoip.dat
        wget -N --no-check-certificate https://raw.githubusercontent.com/xOS/GeoIPs/release/geoip-only-cn-private.dat
 
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
 
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 翠花
        author_email: admin@nange.cn
        message: "Update Country.mmdb"
        add: "-A"
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
